# Generated by Django 2.0.2 on 2018-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin1',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
