# Generated by Django 2.0.2 on 2018-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOT_app', '0002_auto_20181116_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bin3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
